### ISSUE TITLE
Mission != websockets++

### ISSUE THREAD

**Issue by wilaw** [w3c/webtransport-charter#10]
The mission statement sets the tone at the charter stage. It is currently defined as "_The mission of the WebTransport Working Group is to develop APIs that enable data transfer between browsers and servers with richer semantics than those provided by WebSockets (e.g. unreliable messages, avoiding head-of-line blocking)._"

Comments:
1. This is defining WebTransport from the outset as a better version of WebSockets, which seems a bit limiting and unnecessary. 
2. Data transfer could also conceivably occur between two browsers if it were used in a p2p context. Is it more of a point-to-point data transfer between two web-connected endpoints or has the decision already been made to limit scope to browser-server ?

Proposed alternates:
1. The mission of the WebTransport Working Group is to develop APIs that enable data transfer between browsers and servers with support for multiple streams, unidirectional streams, out-of-order delivery, variable reliability and pluggable protocols. 
2. The mission of the WebTransport Working Group is to develop APIs that enable the usage of the IETF WebTransport protocol for browser to server communications.

**Comment by jan-ivar** [comment]
It's my impression p2p is out of scope.

https://datatracker.ietf.org/wg/webtrans/about/ says: _"To assist in the coordination with owners of the WebTransport API, the group will initially develop an overview document containing use cases and requirements in order to clarify the goals of the effort."_

Their [overview document](https://www.ietf.org/id/draft-ietf-webtrans-overview-00.html#name-introduction) talks exclusively about "client" and "server", but seems short on specific use cases.

So it looks like it's that WG owes us use cases & requirements. cc @aboba @martinthomson

**Comment by aboba** [comment]
On Jun 10, 2020, at 11:28, Jan-Ivar Bruaroey <notifications@github.com> wrote:
> 
> ﻿It's my impression p2p is out of scope.

[BA] Right. The charter focus is client/server. There is a P2P spec in ORTC CG that extends the WebTransport API. There was an Origin Trial of it last year based on an earlier version of WebTransport API (pre-WHATWG streams).  Here is the info on that origin trial:
https://developers.google.com/web/updates/2019/01/rtcquictransport-api
Here is a pointer to the P2P spec: 
https://w3c.github.io/webrtc-quic/

> https://datatracker.ietf.org/wg/webtrans/about/ says: "To assist in the coordination with owners of the WebTransport API, the group will initially develop an overview document containing use cases and requirements in order to clarify the goals of the effort."
> 
> Their overview document talks exclusively about "client" and "server", but seems short on specific use cases.
> 
> So it looks like it's that WG owes us use cases & requirements. cc @aboba @martinthomson

[BA] Agree that the current overview document doesn't cover use cases (and non-use cases). There was a discussion of use cases at IETF 106, including: 
Machine learning
Web games
Live streaming
Cloud gaming
Remote desktop
Web chat

The IETF 106 slides are here: 
https://docs.google.com/presentation/d/1njF8fMo9WJ5GU4VYPvI2XBtCqEFQm1l5Gk1b00V6_o/
The IETF 107 slides are here: 
https://docs.google.com/presentation/d/1APFmYij7nyqlmu91R7G61F66pxvWQD5H6UY1W-taRjU/

**Comment by tidoust** [comment]
@wilaw said:

> 1. This is defining WebTransport from the outset as a better version of WebSockets, which seems a bit limiting and unnecessary.

That's a good point. See #11 for a pull request that updates the mission statement with your suggested wording. Pull request is pending approval from W3M reviewers who reviewed the draft.

> 2. Data transfer could also conceivably occur between two browsers if it were used in a p2p context. Is it more of a point-to-point data transfer between two web-connected endpoints or has the decision already been made to limit scope to browser-server ?

As pointed out by @jan-ivar and @aboba, the scope is indeed restricted to browser-server for now.
