### ISSUE TITLE
Few comments on wording

### ISSUE THREAD

**Issue by vasilvv** [w3c/webtransport-charter#14]
"expected to make QUIC endpoints widely available" -- the word "endpoint" sounds a bit weird here.  Maybe "expected tomake QUIC support widely available"?

"when a WebTransport connection cannot be established" -- s/WebTransport/QUIC/.  A WebTransport connection is always a WebTransport connection, even when a TCP fallback is used.

I think "pluggable protocols" is somewhat vague.  We should start with protocols that are produced by IETF webtrans group, but also note that the group MAY take into consideration possibility of use for other protocols when deciding how generic the API should be.

If it makes it easier, I can make a pull request for all of those.

**Comment by dontcallmedom** [comment]
@vasilvv a pull request would be much appreciated - thanks!

**Comment by ylafon** [comment]
All you comments were incorporated, apart from the one about pluggable protocols, which is indeed vague, but the goal is to keep it vague to allow wide use cases to be fulfilled, the WG will decide what the boundaries are at least for v1 of the specification, based on use-cases (There was a presentation of WebTransport use-cases done at IETF recently)
Thanks again!
