### ISSUE TITLE
Deliverables link is broken

### ISSUE THREAD

**Issue by adrianhopebailie** [w3c/webtransport-charter#16]
The charter links to deliverables and milestones at https://www.w3.org/webtransport/ which is a 404

**Comment by tidoust** [comment]
Right, that's the usual chicken and egg situation with charters: a working group charter always links to the group's home page, but that page won't exist until after the group's creation has been approved. We should have flagged these links as "TBD".

**Comment by adrianhopebailie** [comment]
Where is the list though? I'm reviewing the charter and don't know where to find it 😄 
Is there no deliverables list yet at all?

**Comment by tidoust** [comment]
The link to the group's home page at the beginning of section 2 is merely for "More detailed milestones and updated publication schedules", as schedules tend to change after a group gets created.

The "list" (one item in practice, the "WebTransport API") is slightly below that, under [2.1 Normative specifications](https://www.w3.org/2020/06/proposed-webtransport-charter.html#normative).

**Comment by adrianhopebailie** [comment]
Sorry, me not reading properly!
